# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 095a9b6e04a444d4727629e88f8e3cc0f99cd9dd9d7b5695cf3e370df3d93aef6ff10724cc67c9473ed8debfd29daf84d098b2f719a607bbe3a85621f60f4dde

test:
  secret_key_base: 705dd8de07bb2cd427245473ec81bdad3cf2a05d32276d1edc5cc99ddafdc47622076c54482c75681414f2537b2102ee06e0836cc5dbd8225b6cc68c44f50a5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
